spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=bdInmobiliaria;encrypt=true;trustServerCertificate=true
    username: yeler
    password: 12345678
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # Evita que Hibernate cambie la estructura de la base de datos
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Usa los nombres exactos de las tablas y columnas en la base de datos
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  server:
    port: 8080
  tomcat:
    native:
      enabled: true
    protocol-header: x-forwarded-proto
  session:
    store-type: jdbc
    jdbc:
      schema: dbo
      initialize-schema: never
      table-name: tbSesion
      delete-expired-stmt: DELETE FROM tbSesion WHERE ExpirationSesionDate < ?
logging:
  level:
    root: DEBUG
